osx_image: xcode10
language: objective-c
xcode_project: SwiftVideoBackground.xcodeproj

branches:
  only:
    master

before_install:
  - gem install cocoapods
  - gem install xcpretty
  - gem install xcpretty-json-formatter
  - git clone https://github.com/dingwilson/devops-ci.git

script:
  - set -o pipefail

  - xcodebuild clean test -project SwiftVideoBackground.xcodeproj -scheme SwiftVideoBackground -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator, OS=12.0, name=iPhone 7" CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -enableCodeCoverage yes | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild.json" xcpretty -f `xcpretty-json-formatter`

  - bash <(curl -s https://codecov.io/bash)

  - bundle exec danger --fail-on-errors=true

jobs:
  include:
    - stage: jazzy
      script: source ./devops-ci/gen_jazzy_docs.sh
    - stage: cocoapods
      script: pod spec lint
